### PR TITLE
improv: Watch shortcut changes safely

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by ids1024** [comment]
The unsafe code using `FromGlibPtrContainer` would be unnecessary in the next glib-rs. But yeah, this is probably overall a bit clearer and more maintainable.

**Comment by ids1024** [comment]
Building from this branch, I don't seem to be seeing it show the keybinding change when I edit one in Gnome Control Center.

**Comment by mmstick** [comment]
Probably broke it on the last rebase

**Comment by mmstick** [comment]
Okay, it's working now.

**Comment by ids1024** [comment]
Unlike my previous implementation this doesn't seem to handle updates properly when the same gsettings key appears in two places (https://github.com/pop-os/shell-shortcuts/issues/34).

**Comment by mmstick** [comment]
Right, I'll fix that

**Pull request merged**
