### PR TITLE
The hide window shortcut was not documented.

### PR DESCRIPTION
**Pull request by timrichardson**
I added the shortcut for hide window.

### CODE REVIEW

**Comment by maria-komarova** [comment]
I thought we disabled that shortcut by default but maybe I remember wrong.

**Comment by ids1024** [comment]
On my recent Pop!_OS install, `<Super>,` doesn't seem to be bound to anything. By "hide window", do you mean "minimize"? Pop-session [seems to disable that binding](https://github.com/pop-os/session/blob/master/debian/pop-session.gsettings-override).

**Comment by maria-komarova** [comment]
Yes, minimize window is called hide window in GNOME.

**Comment by WatchMkr** [comment]
Thanks for the PR. We've removed hide window by default so won't be adding it to pop-shortcuts.

**Pull request closed without merging**
